version: '3.3'
services:
  elasticsearch:
    image: elasticsearch:5.6.8
    container_name: es
    restart: always
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      cluster.name: elasticsearch